### ISSUE TITLE
SpanBuilder must also look for an ActiveSpan in Start()

### ISSUE THREAD

**Issue by cwe1ss** [Chatham/LetsTrace#12]
Right now, only [`StartActive()`](https://github.com/Chatham/LetsTrace/blob/e680cf0a3679e5a40295e9ab386c84fb61ec3578/src/LetsTrace/SpanBuilder.cs#L55) takes an existing `tracer.ActiveSpan` as a parent. However, this must also be done in the regular `Start()` method. The only difference between `Start()` and `StartActive()` is that `StartActive()` *activates* the newly created span.

See: [Implementation in Jaeger](https://github.com/jaegertracing/jaeger-client-java/blob/d69c2d3333da79d7eb1ffdf982186de5b5f1f4bc/jaeger-core/src/main/java/com/uber/jaeger/Tracer.java#L395) and [related upcoming specification](https://github.com/opentracing/specification/pull/108)

**Comment by Falco20019** [comment]
@SilverXXX Thanks for finding!
@cwe1ss Thanks for reporting and the PR!
