### ISSUE TITLE
Add a build script for local execution and use it in AppVeyor

### ISSUE THREAD

**Issue by cwe1ss** [Chatham/LetsTrace#20]
Would be nice to have a `build.ps1` file which restores/builds/packs/tests locally. This would ensure we can submit PRs that don't fail on AppVeyor. AppVeyor should then also only call this script.

I'd be happy to send a PR with the script I'm using for several projects - e.g. in [opentracing-csharp](https://github.com/opentracing/opentracing-csharp/blob/master/build.ps1) if you like it. It's a simple script that doesn't have any dependencies on e.g. psake, cake, ... but still delivers a nice output. It's also faster than the current AppVeyor script as it does restore/build/pack in one call.

**Comment by grounded042** [comment]
I think this is a good idea. I don't like when AppVeyor can fail but nothing did locally.
