### ISSUE TITLE
LetsTrace.Jaeger still contains `Field`

### ISSUE THREAD

**Issue by grounded042** [Chatham/LetsTrace#30]
With the removal of `Field` in #24 the LetsTrace.Jaeger project broke. Lets fix that.

**Comment by cwe1ss** [comment]
Will you fix it or should I? It should now be possible to use the `case byte[] value` syntax in the `JaegerFieldExtensions.Marshal` method.

**Comment by grounded042** [comment]
I've got it open now and I'll take care of it. Was actually thinking of moving it to a static method since I don't feel like it's the best idea to put an extension method out there for `object`.

**Comment by grounded042** [comment]
And I did remember you mentioned that new switch syntax which is so nice.

**Comment by grounded042** [comment]
Unrelated to this specifically, but with moving ILRepack into the .csproj this no longer builds on MacOS for me. Not a big deal, but might be nice to figure that out. Not sure if there is a way to repack on MacOS.

**Comment by cwe1ss** [comment]
What error do you get? I can have a look at this.

**Comment by grounded042** [comment]
@cwe1ss the error is `LetsTrace/src/LetsTrace.Jaeger/LetsTrace.Jaeger.csproj(34,5): error MSB3073: The command "\.nuget\packages\ILRepack\2.0.15\tools\ilrepack.exe /parallel /internalize /out:LetsTrace.Jaeger.dll LetsTrace.Jaeger.dll Thrift.dll Jaeger.Thrift.dll" exited with code 127.`

It's probably because ILRepack is an exe that won't run on MacOS. Also for what it's worth Visual Studio on Windows doesn't understand that we are packing the dlls on build and so the LetsTrace.Jaeger.Tests project shows a bunch of errors for missing types that don't actually happen at compile time since DLLs are packed into the LetsTrace.Jaeger dll.
