### ISSUE TITLE
Support Third Party Propagation 

### ISSUE THREAD

**Issue by grounded042** [Chatham/LetsTrace#4]
In order to more fully support third party tracing systems we need to have something along the lines of a propagation registry like the Java client has.

**Comment by Falco20019** [comment]
Should be done by merging #5 since we have [Propagation/IPropagationRegistry.cs](https://github.com/Chatham/LetsTrace/blob/master/src/LetsTrace/Propagation/IPropagationRegistry.cs) now.

**Comment by grounded042** [comment]
Yup, closing.
